from aiogram.types import ReplyKeyboardMarkup, KeyboardButton


kb1 = ReplyKeyboardMarkup(resize_keyboard=True)
b1 = KeyboardButton('Кросівки_жін')
b2 = KeyboardButton('Кеди_жін')
b3 = KeyboardButton('Сандалі_жін')
b4 = KeyboardButton('Туфлі_на_підборах')
b5 = KeyboardButton('Чоботи_жін')
b6 = KeyboardButton('Балетки')
b7 = KeyboardButton('Кросівки_чол')
b8 = KeyboardButton('Кеди_чол')
b9 = KeyboardButton('Сандалі_чол')
b10 = KeyboardButton('Шльопанці_чол')
b11 = KeyboardButton('Чоботи_чол')
b12 = KeyboardButton('Туфлі_чол')
b13 = KeyboardButton('Кросівки_дитячі_хлопчачі')
b14 = KeyboardButton('Гумове_взуття_дитяче_хлопчаче')
b15 = KeyboardButton('Черевики_дитячі_хлопчачі')
b16 = KeyboardButton('Мокасини_дитячі_хлопчачі')
b17 = KeyboardButton('Мешти_дитячі_хлопчачі')
b18 = KeyboardButton('Босоніжки_і_сандалі_дитячі_хлопчачі')
b19 = KeyboardButton('Кросівки_дитячі_дівчачі')
b20 = KeyboardButton('Гумове_взуття_дитяче_дівчаче')
b21 = KeyboardButton('Черевики_дитячі_дівчачі')
b22 = KeyboardButton('Мокасини_дитячі_дівчачі')
b23 = KeyboardButton('Мешти_дитячі_дівчачі')
b24 = KeyboardButton('Босоніжки_і_сандалі_дитячі_дівчачі')
kb1.add(b1).insert(b2).insert(b3).add(b4).insert(b5).insert(b6).add(b7).insert(b8).insert(b9).add(b10).insert(b11).insert(b12).add(b13).insert(b14).insert(b15).add(b16).insert(b17).insert(b18).add(b19).insert(b20).insert(b21).add(b22).insert(b23).insert(b24)


kb2 = ReplyKeyboardMarkup(resize_keyboard=True)
b1 = KeyboardButton('19')
b2 = KeyboardButton('20')
b3 = KeyboardButton('21')
b4 = KeyboardButton('22')
b5 = KeyboardButton('23')
b6 = KeyboardButton('24')
b7 = KeyboardButton('25')
b8 = KeyboardButton('26')
b9 = KeyboardButton('27')
b10 = KeyboardButton('28')
b11 = KeyboardButton('29')
b12 = KeyboardButton('30')
b13 = KeyboardButton('31')
b14 = KeyboardButton('32')
b15 = KeyboardButton('33')
b16 = KeyboardButton('34')
b17 = KeyboardButton('35')
b18 = KeyboardButton('36')
b19 = KeyboardButton('37')
b20 = KeyboardButton('38')
b21 = KeyboardButton('39')
b22 = KeyboardButton('40')
b23 = KeyboardButton('41')
b24 = KeyboardButton('42')
b25 = KeyboardButton('43')
b26 = KeyboardButton('44')
b27 = KeyboardButton('45')
b28 = KeyboardButton('46')
kb2.add(b1).insert(b2).insert(b3).add(b4).insert(b5).insert(b6).add(b7).insert(b8).insert(b9).add(b10).insert(b11).insert(b12).add(b13).insert(b14)\
    .insert(b15).add(b16).insert(b17).insert(b18).add(b19).insert(b20).insert(b21).add(b22).insert(b23).insert(b24).add(b25).insert(b26).insert(b27).add(b28)

kb3 = ReplyKeyboardMarkup(resize_keyboard=True)
b1 = KeyboardButton('Доросле')
b2 = KeyboardButton('Дитяче')
kb3.add(b1).insert(b2)

kb4 = ReplyKeyboardMarkup(resize_keyboard=True)
b1 = KeyboardButton('Чоловіче')
b2 = KeyboardButton('Унісекс')
b3 = KeyboardButton('Жіноче')
b4 = KeyboardButton('На_хлопчика')
b5 = KeyboardButton('На_дівчинку')
kb4.add(b1).insert(b2).insert(b3).add(b4).insert(b5)


